sumo:
  seconds: 10000
  min_green: 5
  delta_time: 5
  #sumo_seed: 170701
  further_cmd_args:
    - --junction-taz
    - --delay 5
    - --ignore-junction-blocker 120
agents:
  fixed:
    cycle_time: 6
  ql:
    alpha: 0.10
    gamma: 0.90
    initial_epsilon: 0.05
    min_epsilon: 0.005
    decay: 1
training:
  seconds: 100000
evaluation:
  seconds: 100000
demo:
  seconds: 100000
scenario: ./scenarios/celoria
artifacts:
  agents: ./outputs/agents
  metrics: ./outputs/metrics
  plots: ./outputs/plots
