network: network.net.xml
routes:
  training:
  - training/routes.0.rou.xml
  - training/routes.1.rou.xml
  - training/routes.2.rou.xml
  - training/routes.3.rou.xml
  - training/routes.4.rou.xml
  - training/routes.5.rou.xml
  - training/routes.6.rou.xml
  - training/routes.7.rou.xml
  - training/routes.8.rou.xml
  - training/routes.9.rou.xml
  - training/routes.10.rou.xml
  - training/routes.11.rou.xml
  - training/routes.12.rou.xml
  - training/routes.13.rou.xml
  - training/routes.14.rou.xml
  - training/routes.15.rou.xml
  - training/routes.16.rou.xml
  - training/routes.17.rou.xml
  - training/routes.18.rou.xml
  - training/routes.19.rou.xml
  - training/routes.20.rou.xml
  - training/routes.21.rou.xml
  - training/routes.22.rou.xml
  - training/routes.23.rou.xml
  - training/routes.24.rou.xml
  - training/routes.25.rou.xml
  - training/routes.26.rou.xml
  - training/routes.27.rou.xml
  - training/routes.28.rou.xml
  - training/routes.29.rou.xml
  - training/routes.30.rou.xml
  - training/routes.31.rou.xml
  - training/routes.32.rou.xml
  - training/routes.33.rou.xml
  - training/routes.34.rou.xml
  - training/routes.35.rou.xml
  - training/routes.36.rou.xml
  - training/routes.37.rou.xml
  - training/routes.38.rou.xml
  - training/routes.39.rou.xml
  - training/routes.40.rou.xml
  - training/routes.41.rou.xml
  - training/routes.42.rou.xml
  - training/routes.43.rou.xml
  - training/routes.44.rou.xml
  - training/routes.45.rou.xml
  - training/routes.46.rou.xml
  - training/routes.47.rou.xml
  - training/routes.48.rou.xml
  - training/routes.49.rou.xml
  - training/routes.50.rou.xml
  - training/routes.51.rou.xml
  - training/routes.52.rou.xml
  - training/routes.53.rou.xml
  - training/routes.54.rou.xml
  - training/routes.55.rou.xml
  - training/routes.56.rou.xml
  - training/routes.57.rou.xml
  - training/routes.58.rou.xml
  - training/routes.59.rou.xml
  - training/routes.60.rou.xml
  - training/routes.61.rou.xml
  - training/routes.62.rou.xml
  - training/routes.63.rou.xml
  - training/routes.64.rou.xml
  - training/routes.65.rou.xml
  - training/routes.66.rou.xml
  - training/routes.67.rou.xml
  - training/routes.68.rou.xml
  - training/routes.69.rou.xml
  - training/routes.70.rou.xml
  - training/routes.71.rou.xml
  - training/routes.72.rou.xml
  - training/routes.73.rou.xml
  - training/routes.74.rou.xml
  - training/routes.75.rou.xml
  - training/routes.76.rou.xml
  - training/routes.77.rou.xml
  - training/routes.78.rou.xml
  - training/routes.79.rou.xml
  - training/routes.80.rou.xml
  - training/routes.81.rou.xml
  - training/routes.82.rou.xml
  - training/routes.83.rou.xml
  - training/routes.84.rou.xml
  - training/routes.85.rou.xml
  - training/routes.86.rou.xml
  - training/routes.87.rou.xml
  - training/routes.88.rou.xml
  - training/routes.89.rou.xml
  - training/routes.90.rou.xml
  - training/routes.91.rou.xml
  - training/routes.92.rou.xml
  - training/routes.93.rou.xml
  - training/routes.94.rou.xml
  - training/routes.95.rou.xml
  - training/routes.96.rou.xml
  - training/routes.97.rou.xml
  - training/routes.98.rou.xml
  - training/routes.99.rou.xml
  - training/routes.100.rou.xml
  - training/routes.101.rou.xml
  - training/routes.102.rou.xml
  - training/routes.103.rou.xml
  - training/routes.104.rou.xml
  - training/routes.105.rou.xml
  - training/routes.106.rou.xml
  - training/routes.107.rou.xml
  - training/routes.108.rou.xml
  - training/routes.109.rou.xml
  - training/routes.110.rou.xml
  - training/routes.111.rou.xml
  - training/routes.112.rou.xml
  - training/routes.113.rou.xml
  - training/routes.114.rou.xml
  - training/routes.115.rou.xml
  - training/routes.116.rou.xml
  - training/routes.117.rou.xml
  - training/routes.118.rou.xml
  - training/routes.119.rou.xml
  - training/routes.120.rou.xml
  - training/routes.121.rou.xml
  - training/routes.122.rou.xml
  - training/routes.123.rou.xml
  - training/routes.124.rou.xml
  - training/routes.125.rou.xml
  - training/routes.126.rou.xml
  - training/routes.127.rou.xml
  - training/routes.128.rou.xml
  - training/routes.129.rou.xml
  - training/routes.130.rou.xml
  - training/routes.131.rou.xml
  - training/routes.132.rou.xml
  - training/routes.133.rou.xml
  - training/routes.134.rou.xml
  - training/routes.135.rou.xml
  - training/routes.136.rou.xml
  - training/routes.137.rou.xml
  - training/routes.138.rou.xml
  - training/routes.139.rou.xml
  - training/routes.140.rou.xml
  - training/routes.141.rou.xml
  - training/routes.142.rou.xml
  - training/routes.143.rou.xml
  - training/routes.144.rou.xml
  - training/routes.145.rou.xml
  - training/routes.146.rou.xml
  - training/routes.147.rou.xml
  - training/routes.148.rou.xml
  - training/routes.149.rou.xml
  - training/routes.150.rou.xml
  - training/routes.151.rou.xml
  - training/routes.152.rou.xml
  - training/routes.153.rou.xml
  - training/routes.154.rou.xml
  - training/routes.155.rou.xml
  - training/routes.156.rou.xml
  - training/routes.157.rou.xml
  - training/routes.158.rou.xml
  - training/routes.159.rou.xml
  - training/routes.160.rou.xml
  - training/routes.161.rou.xml
  - training/routes.162.rou.xml
  - training/routes.163.rou.xml
  - training/routes.164.rou.xml
  - training/routes.165.rou.xml
  - training/routes.166.rou.xml
  - training/routes.167.rou.xml
  - training/routes.168.rou.xml
  - training/routes.169.rou.xml
  - training/routes.170.rou.xml
  - training/routes.171.rou.xml
  - training/routes.172.rou.xml
  - training/routes.173.rou.xml
  - training/routes.174.rou.xml
  - training/routes.175.rou.xml
  - training/routes.176.rou.xml
  - training/routes.177.rou.xml
  - training/routes.178.rou.xml
  - training/routes.179.rou.xml
  - training/routes.180.rou.xml
  - training/routes.181.rou.xml
  - training/routes.182.rou.xml
  - training/routes.183.rou.xml
  - training/routes.184.rou.xml
  - training/routes.185.rou.xml
  - training/routes.186.rou.xml
  - training/routes.187.rou.xml
  - training/routes.188.rou.xml
  - training/routes.189.rou.xml
  - training/routes.190.rou.xml
  - training/routes.191.rou.xml
  - training/routes.192.rou.xml
  - training/routes.193.rou.xml
  - training/routes.194.rou.xml
  - training/routes.195.rou.xml
  - training/routes.196.rou.xml
  - training/routes.197.rou.xml
  - training/routes.198.rou.xml
  - training/routes.199.rou.xml
  - training/routes.200.rou.xml
  - training/routes.201.rou.xml
  - training/routes.202.rou.xml
  - training/routes.203.rou.xml
  - training/routes.204.rou.xml
  - training/routes.205.rou.xml
  - training/routes.206.rou.xml
  - training/routes.207.rou.xml
  - training/routes.208.rou.xml
  - training/routes.209.rou.xml
  - training/routes.210.rou.xml
  - training/routes.211.rou.xml
  - training/routes.212.rou.xml
  - training/routes.213.rou.xml
  - training/routes.214.rou.xml
  - training/routes.215.rou.xml
  - training/routes.216.rou.xml
  - training/routes.217.rou.xml
  - training/routes.218.rou.xml
  - training/routes.219.rou.xml
  - training/routes.220.rou.xml
  - training/routes.221.rou.xml
  - training/routes.222.rou.xml
  - training/routes.223.rou.xml
  - training/routes.224.rou.xml
  - training/routes.225.rou.xml
  - training/routes.226.rou.xml
  - training/routes.227.rou.xml
  - training/routes.228.rou.xml
  - training/routes.229.rou.xml
  - training/routes.230.rou.xml
  - training/routes.231.rou.xml
  - training/routes.232.rou.xml
  - training/routes.233.rou.xml
  - training/routes.234.rou.xml
  - training/routes.235.rou.xml
  - training/routes.236.rou.xml
  - training/routes.237.rou.xml
  - training/routes.238.rou.xml
  - training/routes.239.rou.xml
  evaluation:
  - evaluation/routes.0.rou.xml
  - evaluation/routes.1.rou.xml
  - evaluation/routes.2.rou.xml
  - evaluation/routes.3.rou.xml
  - evaluation/routes.4.rou.xml
  - evaluation/routes.5.rou.xml
  - evaluation/routes.6.rou.xml
  - evaluation/routes.7.rou.xml
  - evaluation/routes.8.rou.xml
  - evaluation/routes.9.rou.xml
  - evaluation/routes.10.rou.xml
  - evaluation/routes.11.rou.xml
  - evaluation/routes.12.rou.xml
  - evaluation/routes.13.rou.xml
  - evaluation/routes.14.rou.xml
  - evaluation/routes.15.rou.xml
  - evaluation/routes.16.rou.xml
  - evaluation/routes.17.rou.xml
  - evaluation/routes.18.rou.xml
  - evaluation/routes.19.rou.xml
  - evaluation/routes.20.rou.xml
  - evaluation/routes.21.rou.xml
  - evaluation/routes.22.rou.xml
  - evaluation/routes.23.rou.xml
  - evaluation/routes.24.rou.xml
  - evaluation/routes.25.rou.xml
  - evaluation/routes.26.rou.xml
  - evaluation/routes.27.rou.xml
  - evaluation/routes.28.rou.xml
  - evaluation/routes.29.rou.xml
  - evaluation/routes.30.rou.xml
  - evaluation/routes.31.rou.xml
  - evaluation/routes.32.rou.xml
  - evaluation/routes.33.rou.xml
  - evaluation/routes.34.rou.xml
  - evaluation/routes.35.rou.xml
  - evaluation/routes.36.rou.xml
  - evaluation/routes.37.rou.xml
  - evaluation/routes.38.rou.xml
  - evaluation/routes.39.rou.xml
  - evaluation/routes.40.rou.xml
  - evaluation/routes.41.rou.xml
  - evaluation/routes.42.rou.xml
  - evaluation/routes.43.rou.xml
  - evaluation/routes.44.rou.xml
  - evaluation/routes.45.rou.xml
  - evaluation/routes.46.rou.xml
  - evaluation/routes.47.rou.xml
  - evaluation/routes.48.rou.xml
  - evaluation/routes.49.rou.xml
  - evaluation/routes.50.rou.xml
  - evaluation/routes.51.rou.xml
  - evaluation/routes.52.rou.xml
  - evaluation/routes.53.rou.xml
  - evaluation/routes.54.rou.xml
  - evaluation/routes.55.rou.xml
  - evaluation/routes.56.rou.xml
  - evaluation/routes.57.rou.xml
  - evaluation/routes.58.rou.xml
  - evaluation/routes.59.rou.xml
  - evaluation/routes.60.rou.xml
  - evaluation/routes.61.rou.xml
  - evaluation/routes.62.rou.xml
  - evaluation/routes.63.rou.xml
  - evaluation/routes.64.rou.xml
  - evaluation/routes.65.rou.xml
  - evaluation/routes.66.rou.xml
  - evaluation/routes.67.rou.xml
  - evaluation/routes.68.rou.xml
  - evaluation/routes.69.rou.xml
  - evaluation/routes.70.rou.xml
  - evaluation/routes.71.rou.xml
  - evaluation/routes.72.rou.xml
  - evaluation/routes.73.rou.xml
  - evaluation/routes.74.rou.xml
  - evaluation/routes.75.rou.xml
  - evaluation/routes.76.rou.xml
  - evaluation/routes.77.rou.xml
  - evaluation/routes.78.rou.xml
  - evaluation/routes.79.rou.xml
  - evaluation/routes.80.rou.xml
  - evaluation/routes.81.rou.xml
  - evaluation/routes.82.rou.xml
  - evaluation/routes.83.rou.xml
  - evaluation/routes.84.rou.xml
  - evaluation/routes.85.rou.xml
  - evaluation/routes.86.rou.xml
  - evaluation/routes.87.rou.xml
  - evaluation/routes.88.rou.xml
  - evaluation/routes.89.rou.xml
  - evaluation/routes.90.rou.xml
  - evaluation/routes.91.rou.xml
  - evaluation/routes.92.rou.xml
  - evaluation/routes.93.rou.xml
  - evaluation/routes.94.rou.xml
  - evaluation/routes.95.rou.xml
  - evaluation/routes.96.rou.xml
  - evaluation/routes.97.rou.xml
  - evaluation/routes.98.rou.xml
  - evaluation/routes.99.rou.xml
  demo:
    - routes.rou.xml
