network: network.net.xml
routes:
  training:
  - training/order.yml
  evaluation:
  - evaluation/order.yml
  demo:
  - evaluation/order.yml
layout:
  main:
    - A: J0
      B: J3
  side:
    - A: J4
      B: J5
    - A: J6
      B: J7
