network: network.net.xml
routes:
  training:
  - training/order.yml
  evaluation:
  - evaluation/order.yml
  demo:
  - evaluation/order.yml
layout:
  main:
    - A: J2
      B: J16
  side:
    - A: J3
      B: J0
    - A: J6
      B: J8
    - A: J7
      B: J9
    - A: J12
      B: J13
    - A: J15
      B: J14
