network: network.net.xml
routes:
  training:
    - routes.rou.xml
  evaluation:
    - routes.rou.xml
  demo:
    - routes.rou.xml
layout:
  main:
    - A: J0
      B: J3
  side:
    - A: J2
      B: J4
