if __name__ == "__main__":
  print("Available tools:")
  print("> tools.cityflow2sumo")
  print("> tools.amma2cityflow")
  print("> tools.amma2sumo")
  print("> tools.compare-global-metrics")
  print("> tools.compare-directional-metrics")
  print("> tools.extract-global-metrics")
  print("> tools.extract-directional-metrics")
  print("> tools.plot-global-metrics")
  print("> tools.plot-smoothed-metrics")
  print("> tools.plot-directional-metrics")
  print("> tools.generate-flows")
  print("> tools.generate-topology")
  print("> tools.executor")
